[package]
name = "kanban-graph-oxigraph"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kanban-local.workspace = true
kanban-indexer.workspace = true
clap.workspace = true
anyhow.workspace = true
kanban-entity.workspace = true
kanban-derived-io.workspace = true
kanban-helper-protocol.workspace = true
kanban-graph.workspace = true
oxigraph.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
