/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/astryx.ts
 * Command: astryx theme build src/theme/astryx.ts
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

/// <reference path="./astryx.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const astryxTheme: DefinedTheme;
