//! 完整具名业务 RPC：生成契约与共享 application service 之间的显式接线。
use super::context::{call_context, invalid_request, response_codec_error, service_error};
use crate::{AppState, application as app};
use kanban_protocol::rpc::v1::{self, kanban_service_server::KanbanService};
use tonic::{Request, Response, Status};

#[derive(Clone)]
pub(super) struct BusinessRpc {
    pub state: AppState,
}

macro_rules! implement_service {
    ($( $method:ident($request:ident => $response:ident)
        ($state:ident, $context:ident; $path:pat, $query:pat, $input:pat) => $call:expr; )*) => {
        #[cfg(test)]
        pub(crate) const REGISTERED_REQUESTS: &[&str] = &[$(stringify!($request)),*];
        #[tonic::async_trait]
        impl KanbanService for BusinessRpc {
            $(async fn $method(&self, request: Request<v1::$request>) -> Result<Response<v1::$response>, Status> {
                let $context = call_context(request.metadata())?;
                let ($path, $query, $input) = request.into_inner().decode_parts().map_err(invalid_request)?;
                let $state = self.state.clone();
                let value = $call.await.map_err(service_error)?;
                let response = value.try_into().map_err(response_codec_error)?;
                Ok(Response::new(response))
            })*
        }
    };
}

implement_service! {
    get_health(GetHealthRequest => GetHealthResponse)
        (state, _context; _, _, _) => app::health::get_health(state);
    list_boards(ListBoardsRequest => ListBoardsResponse)
        (state, _context; _, query, _) => app::boards::list::list_boards(state, query);
    create_board(CreateBoardRequest => CreateBoardResponse)
        (state, context; _, _, input) => app::boards::create::create_board(state, context, input);
    get_board(GetBoardRequest => GetBoardResponse)
        (state, _context; path, _, _) => app::boards::get::get_board(state, path);
    archive_board(ArchiveBoardRequest => ArchiveBoardResponse)
        (state, context; path, _, input) => app::boards::archive::archive_board(state, path, context, input);
    list_board_columns(ListBoardColumnsRequest => ListBoardColumnsResponse)
        (state, _context; path, _, _) => app::boards::columns::list_board_columns(state, path);
    list_tasks(ListTasksRequest => ListTasksResponse)
        (state, _context; path, query, _) => app::tasks::list::list_tasks(state, path, query);
    list_tasks_by_status(ListTasksByStatusRequest => ListTasksByStatusResponse)
        (state, _context; path, query, _) => app::tasks::list::list_tasks_by_status(state, path, query);
    create_task(CreateTaskRequest => CreateTaskResponse)
        (state, context; path, _, input) => app::tasks::create::create_task(state, path, context, input);
    get_task(GetTaskRequest => GetTaskResponse)
        (state, _context; path, query, _) => app::tasks::show::get_task(state, path, query);
    update_task(UpdateTaskRequest => UpdateTaskResponse)
        (state, context; path, _, input) => app::tasks::update::update_task(state, path, context, input);
    specify_task(SpecifyTaskRequest => SpecifyTaskResponse)
        (state, context; path, _, input) => app::tasks::specify::specify_task(state, path, context, input);
    promote_task(PromoteTaskRequest => PromoteTaskResponse)
        (state, context; path, _, input) => app::tasks::promote::promote_task(state, path, context, input);
    claim_task(ClaimTaskRequest => ClaimTaskResponse)
        (state, context; path, _, input) => app::tasks::claim::claim_task(state, path, context, input);
    reopen_task(ReopenTaskRequest => ReopenTaskResponse)
        (state, context; path, _, input) => app::tasks::reopen::reopen_task(state, path, context, input);
    reclaim_task(ReclaimTaskRequest => ReclaimTaskResponse)
        (state, context; path, _, input) => app::tasks::reclaim::reclaim_task(state, path, context, input);
    heartbeat_task(HeartbeatTaskRequest => HeartbeatTaskResponse)
        (state, context; path, _, input) => app::tasks::heartbeat::heartbeat_task(state, path, context, input);
    release_task(ReleaseTaskRequest => ReleaseTaskResponse)
        (state, context; path, _, input) => app::tasks::release::release_task(state, path, context, input);
    complete_task(CompleteTaskRequest => CompleteTaskResponse)
        (state, context; path, _, input) => app::tasks::done::complete_task(state, path, context, input);
    submit_review_task(SubmitReviewTaskRequest => SubmitReviewTaskResponse)
        (state, context; path, _, input) => app::tasks::review::submit_review_task(state, path, context, input);
    block_task(BlockTaskRequest => BlockTaskResponse)
        (state, context; path, _, input) => app::tasks::block::block_task(state, path, context, input);
    unblock_task(UnblockTaskRequest => UnblockTaskResponse)
        (state, context; path, _, input) => app::tasks::unblock::unblock_task(state, path, context, input);
    archive_task(ArchiveTaskRequest => ArchiveTaskResponse)
        (state, context; path, _, input) => app::tasks::archive::archive_task(state, path, context, input);
    list_steps(ListStepsRequest => ListStepsResponse)
        (state, _context; path, _, _) => app::steps::list::list_steps(state, path);
    create_step(CreateStepRequest => CreateStepResponse)
        (state, context; path, _, input) => app::steps::create::create_step(state, path, context, input);
    update_step(UpdateStepRequest => UpdateStepResponse)
        (state, context; path, _, input) => app::steps::update::update_step(state, path, context, input);
    remove_step(RemoveStepRequest => RemoveStepResponse)
        (state, context; path, _, _) => app::steps::remove::remove_step(state, path, context);
    complete_step(CompleteStepRequest => CompleteStepResponse)
        (state, context; path, _, input) => app::steps::resolve::complete_step(state, path, context, input);
    skip_step(SkipStepRequest => SkipStepResponse)
        (state, context; path, _, input) => app::steps::resolve::skip_step(state, path, context, input);
    reopen_step(ReopenStepRequest => ReopenStepResponse)
        (state, context; path, _, input) => app::steps::resolve::reopen_step(state, path, context, input);
    mark_execution_plan_not_required(MarkExecutionPlanNotRequiredRequest => MarkExecutionPlanNotRequiredResponse)
        (state, context; path, _, input) => app::tasks::plan_not_required::mark_execution_plan_not_required(state, path, context, input);
    list_dependencies(ListDependenciesRequest => ListDependenciesResponse)
        (state, _context; path, _, _) => app::dependencies::list::list_dependencies(state, path);
    add_dependency(AddDependencyRequest => AddDependencyResponse)
        (state, context; path, _, input) => app::dependencies::create::add_dependency(state, path, context, input);
    remove_dependency(RemoveDependencyRequest => RemoveDependencyResponse)
        (state, context; path, _, _) => app::dependencies::remove::remove_dependency(state, path, context);
    list_runs(ListRunsRequest => ListRunsResponse)
        (state, _context; path, _, _) => app::runs::list::list_runs(state, path);
    get_run(GetRunRequest => GetRunResponse)
        (state, _context; path, _, _) => app::runs::show::get_run(state, path);
    get_run_log(GetRunLogRequest => GetRunLogResponse)
        (state, _context; path, _, _) => app::runs::log::get_run_log(state, path);
    list_comments(ListCommentsRequest => ListCommentsResponse)
        (state, _context; path, _, _) => app::comments::list::list_comments(state, path);
    create_comment(CreateCommentRequest => CreateCommentResponse)
        (state, context; path, _, input) => app::comments::create::create_comment(state, path, context, input);
    list_attachments(ListAttachmentsRequest => ListAttachmentsResponse)
        (state, _context; path, _, _) => app::attachments::list_attachments(state, path);
    create_attachment(CreateAttachmentRequest => CreateAttachmentResponse)
        (state, context; path, _, input) => app::attachments::create_attachment(state, path, context, input);
    download_attachment(DownloadAttachmentRequest => DownloadAttachmentResponse)
        (state, _context; path, _, _) => async { app::attachments::download_attachment(state, path).await.map(kanban_protocol::rpc::dto::AttachmentDownload::from) };
    delete_attachment(DeleteAttachmentRequest => DeleteAttachmentResponse)
        (state, context; path, _, _) => app::attachments::delete_attachment(state, path, context);
    list_events(ListEventsRequest => ListEventsResponse)
        (state, _context; _, query, _) => app::events::list::list_events(state, query);
    list_task_labels(ListTaskLabelsRequest => ListTaskLabelsResponse)
        (state, _context; path, _, _) => app::labels::list_task_labels(state, path);
    add_task_label(AddTaskLabelRequest => AddTaskLabelResponse)
        (state, context; path, _, input) => app::labels::add_task_labels(state, path, context, input);
    bootstrap_task_label(BootstrapTaskLabelRequest => BootstrapTaskLabelResponse)
        (state, context; path, _, input) => app::labels::bootstrap_task_label(state, path, context, input);
    remove_task_label(RemoveTaskLabelRequest => RemoveTaskLabelResponse)
        (state, context; path, _, _) => app::labels::remove_task_label(state, path, context);
    list_board_labels(ListBoardLabelsRequest => ListBoardLabelsResponse)
        (state, _context; path, _, _) => app::labels::list_board_labels(state, path);
    list_board_label_proposals(ListBoardLabelProposalsRequest => ListBoardLabelProposalsResponse)
        (state, _context; path, query, _) => app::ontology::list_proposals_for_board(state, path, query);
    create_board_label(CreateBoardLabelRequest => CreateBoardLabelResponse)
        (state, _context; path, _, input) => app::labels::create_board_label(state, path, input);
    delete_board_label(DeleteBoardLabelRequest => DeleteBoardLabelResponse)
        (state, context; path, query, _) => app::labels::delete_board_label(state, path, context, query);
    list_label_semantics(ListLabelSemanticsRequest => ListLabelSemanticsResponse)
        (state, _context; path, _, _) => app::ontology::list_semantics(state, path);
    get_label_semantics(GetLabelSemanticsRequest => GetLabelSemanticsResponse)
        (state, _context; path, _, _) => app::ontology::get_semantics(state, path);
    upsert_label_semantics(UpsertLabelSemanticsRequest => UpsertLabelSemanticsResponse)
        (state, context; path, _, input) => app::ontology::upsert_semantics(state, path, context, input);
    delete_label_semantics(DeleteLabelSemanticsRequest => DeleteLabelSemanticsResponse)
        (state, context; path, query, _) => app::ontology::delete_semantics(state, path, context, query);
    list_label_atoms(ListLabelAtomsRequest => ListLabelAtomsResponse)
        (state, _context; path, _, _) => app::ontology::list_atoms(state, path);
    explain_label_atom(ExplainLabelAtomRequest => ExplainLabelAtomResponse)
        (state, _context; path, _, _) => app::ontology::explain_atom(state, path);
    label_atom_index_status(LabelAtomIndexStatusRequest => LabelAtomIndexStatusResponse)
        (state, _context; path, _, _) => app::ontology::index_status(state, path);
    rebuild_label_atom_index(RebuildLabelAtomIndexRequest => RebuildLabelAtomIndexResponse)
        (state, _context; path, _, _) => app::ontology::rebuild_index(state, path);
    query_label_atom_index(QueryLabelAtomIndexRequest => QueryLabelAtomIndexResponse)
        (state, _context; path, query, _) => app::ontology::query_index(state, path, query);
    list_signals(ListSignalsRequest => ListSignalsResponse)
        (state, _context; path, query, _) => app::signals::list::list_signals(state, path, query);
    review_signals(ReviewSignalsRequest => ReviewSignalsResponse)
        (state, _context; path, query, _) => app::signals::list::review_signals(state, path, query);
    get_signal(GetSignalRequest => GetSignalResponse)
        (state, _context; path, _, _) => app::signals::show::get_signal(state, path);
    record_signal(RecordSignalRequest => RecordSignalResponse)
        (state, context; path, _, input) => app::signals::record::record_signal(state, path, context, input);
    confirm_signals(ConfirmSignalsRequest => ConfirmSignalsResponse)
        (state, context; path, _, input) => app::signals::review::confirm_signals(state, path, context, input);
    reject_signals(RejectSignalsRequest => RejectSignalsResponse)
        (state, context; path, _, input) => app::signals::review::reject_signals(state, path, context, input);
    resolve_signals(ResolveSignalsRequest => ResolveSignalsResponse)
        (state, context; path, _, input) => app::signals::review::resolve_signals(state, path, context, input);
    supersede_signals(SupersedeSignalsRequest => SupersedeSignalsResponse)
        (state, context; path, _, input) => app::signals::review::supersede_signals(state, path, context, input);
    suggest_task_labels(SuggestTaskLabelsRequest => SuggestTaskLabelsResponse)
        (state, _context; path, query, _) => app::ontology::suggestions(state, path, query);
    list_task_label_proposals(ListTaskLabelProposalsRequest => ListTaskLabelProposalsResponse)
        (state, _context; path, query, _) => app::ontology::list_proposals_for_task(state, path, query);
    propose_task_label(ProposeTaskLabelRequest => ProposeTaskLabelResponse)
        (state, context; path, query, input) => app::ontology::propose_for_task(state, path, context, query, Some(input));
    record_label_ontology_observation(RecordLabelOntologyObservationRequest => RecordLabelOntologyObservationResponse)
        (state, _context; path, query, input) => app::ontology::record_observation(state, path, query, input);
    list_label_ontology_signals(ListLabelOntologySignalsRequest => ListLabelOntologySignalsResponse)
        (state, _context; path, query, _) => app::ontology::list_signals(state, path, query);
    review_label_ontology(ReviewLabelOntologyRequest => ReviewLabelOntologyResponse)
        (state, _context; path, query, _) => app::ontology::review_signals(state, path, query);
    create_label_ontology_action(CreateLabelOntologyActionRequest => CreateLabelOntologyActionResponse)
        (state, _context; path, _, input) => app::ontology::create_action(state, path, input);
    apply_label_ontology_atom(ApplyLabelOntologyAtomRequest => ApplyLabelOntologyAtomResponse)
        (state, _context; path, _, input) => app::ontology::apply_atom(state, path, input);
    revert_label_ontology_mutation(RevertLabelOntologyMutationRequest => RevertLabelOntologyMutationResponse)
        (state, _context; path, _, input) => app::ontology::revert(state, path, input);
    validate_label_ontology_action(ValidateLabelOntologyActionRequest => ValidateLabelOntologyActionResponse)
        (state, _context; path, _, input) => app::ontology::validate(state, path, input);
    get_label_ontology_signal(GetLabelOntologySignalRequest => GetLabelOntologySignalResponse)
        (state, _context; path, _, _) => app::ontology::get_signal(state, path);
    get_label_proposal(GetLabelProposalRequest => GetLabelProposalResponse)
        (state, _context; path, _, _) => app::ontology::get_proposal(state, path);
    accept_label_proposal(AcceptLabelProposalRequest => AcceptLabelProposalResponse)
        (state, context; path, _, input) => app::ontology::accept_proposal(state, path, context, input);
    reject_label_proposal(RejectLabelProposalRequest => RejectLabelProposalResponse)
        (state, context; path, _, input) => app::ontology::reject_proposal(state, path, context, input);
    board_task_map(BoardTaskMapRequest => BoardTaskMapResponse)
        (state, _context; path, query, _) => app::graph::board_task_map(state, path, query);
    task_neighborhood(TaskNeighborhoodRequest => TaskNeighborhoodResponse)
        (state, _context; path, query, _) => app::graph::task_neighborhood(state, path, query);
    search_tasks(SearchTasksRequest => SearchTasksResponse)
        (state, _context; _, query, _) => app::search::search_tasks(state, query);
    search_tasks_by_status(SearchTasksByStatusRequest => SearchTasksByStatusResponse)
        (state, _context; _, query, _) => app::search::search_tasks_by_status(state, query);
    search_status(SearchStatusRequest => SearchStatusResponse)
        (state, _context; _, query, _) => app::search::search_status(state, query);
    rebuild_search_index(RebuildSearchIndexRequest => RebuildSearchIndexResponse)
        (state, _context; _, query, _) => app::search::rebuild_search(state, query);
    sync_search_index(SyncSearchIndexRequest => SyncSearchIndexResponse)
        (state, _context; _, query, _) => app::search::sync_search(state, query);
    build_context(BuildContextRequest => BuildContextResponse)
        (state, _context; path, query, _) => app::context::build_context(state, path, query);
    graph_status(GraphStatusRequest => GraphStatusResponse)
        (state, _context; _, query, _) => app::graph::graph_status(state, query);
    graph_neighbors(GraphNeighborsRequest => GraphNeighborsResponse)
        (state, _context; _, query, _) => app::graph::graph_neighbors(state, query);
    graph_query(GraphQueryRequest => GraphQueryResponse)
        (state, _context; _, query, _) => app::graph::graph_query(state, query);
    graph_rebuild(GraphRebuildRequest => GraphRebuildResponse)
        (state, _context; _, query, _) => app::graph::graph_rebuild(state, query);
    graph_sync(GraphSyncRequest => GraphSyncResponse)
        (state, _context; _, query, _) => app::graph::graph_sync(state, query);
    list_entities(ListEntitiesRequest => ListEntitiesResponse)
        (state, _context; _, query, _) => app::entities::list_entities(state, query);
    upsert_entity(UpsertEntityRequest => UpsertEntityResponse)
        (state, _context; _, _, input) => app::entities::upsert_entity(state, input);
    get_entity(GetEntityRequest => GetEntityResponse)
        (state, _context; path, _, _) => app::entities::get_entity(state, path);
    vector_status(VectorStatusRequest => VectorStatusResponse)
        (state, _context; _, query, _) => app::vector::status(state, query);
    vector_configure(VectorConfigureRequest => VectorConfigureResponse)
        (state, _context; _, _, input) => app::vector::configure(state, input);
    vector_rebuild(VectorRebuildRequest => VectorRebuildResponse)
        (state, _context; _, _, input) => app::vector::rebuild(state, input);
    vector_sync(VectorSyncRequest => VectorSyncResponse)
        (state, _context; _, _, input) => app::vector::sync(state, input);
    vector_query_chunks(VectorQueryChunksRequest => VectorQueryChunksResponse)
        (state, _context; _, query, _) => app::vector::query_chunks(state, query);
    vector_query_label_atoms(VectorQueryLabelAtomsRequest => VectorQueryLabelAtomsResponse)
        (state, _context; _, query, _) => app::vector::query_label_atoms(state, query);
    get_stats(GetStatsRequest => GetStatsResponse)
        (state, _context; _, query, _) => app::stats::stats(state, query);
    doctor(DoctorRequest => DoctorResponse)
        (state, _context; _, _, _) => app::maintenance::doctor(state);
    checkpoint(CheckpointRequest => CheckpointResponse)
        (state, _context; _, _, _) => app::maintenance::checkpoint(state);
    maintenance_backup(MaintenanceBackupRequest => MaintenanceBackupResponse)
        (state, _context; _, _, input) => app::maintenance::backup(state, input);
    maintenance_export(MaintenanceExportRequest => MaintenanceExportResponse)
        (state, _context; _, _, input) => app::maintenance::export(state, input);
    maintenance_import(MaintenanceImportRequest => MaintenanceImportResponse)
        (state, _context; _, _, input) => app::maintenance::import(state, input);
    maintenance_vacuum(MaintenanceVacuumRequest => MaintenanceVacuumResponse)
        (state, _context; _, _, _) => app::maintenance::vacuum(state);
    maintenance_status(MaintenanceStatusRequest => MaintenanceStatusResponse)
        (state, _context; _, _, _) => app::maintenance::maintenance_status(state);
    maintenance_run(MaintenanceRunRequest => MaintenanceRunResponse)
        (state, _context; _, _, input) => app::maintenance::maintenance_run(state, input);
    maintenance_rebuild(MaintenanceRebuildRequest => MaintenanceRebuildResponse)
        (state, _context; _, _, input) => app::maintenance::maintenance_rebuild(state, input);
    maintenance_cleanup(MaintenanceCleanupRequest => MaintenanceCleanupResponse)
        (state, _context; _, _, input) => app::maintenance::maintenance_cleanup(state, input);
    maintenance_import_v30(MaintenanceImportV30Request => MaintenanceImportV30Response)
        (state, _context; _, _, input) => app::maintenance::import_legacy_sqlite_v30(state, input);
    get_task_details(GetTaskDetailsRequest => GetTaskDetailsResponse)
        (state, _context; path, _, _) => app::tasks::show::get_task_details(state, path);
    get_label_ontology_quality(GetLabelOntologyQualityRequest => GetLabelOntologyQualityResponse)
        (state, _context; path, query, _) => app::ontology::get_label_ontology_quality(state, path, query.sample_limit);
}
