// 设置页的本地化文案组合；键及参数类型由 catalog 生成。
import { createTranslator } from './runtime';
import type { Locale } from './locale';
export function settingsCopy(locale: Locale) {
 const t=createTranslator(locale);
 return {
  "actor": t("settings-view:actor"),
  "actorPlaceholder": t("settings-view:actorPlaceholder"),
  "appearance": t("settings-view:appearance"),
  "available": t("settings-view:available"),
  "collapsed": t("settings-view:collapsed"),
  "comfortable": t("settings-view:comfortable"),
  "compact": t("settings-view:compact"),
  "connection": t("settings-view:connection"),
  "copy": t("settings-view:copy"),
  "copying": t("settings-view:copying"),
  "dark": t("settings-view:dark"),
  "density": t("settings-view:density"),
  "densityNote": t("settings-view:densityNote"),
  "description": t("settings-view:description"),
  "display": t("settings-view:display"),
  "displayNote": t("settings-view:displayNote"),
  "error": t("settings-view:error"),
  "expanded": t("settings-view:expanded"),
  "health": t("settings-view:health"),
  "healthRetry": t("settings-view:healthRetry"),
  "identity": t("settings-view:identity"),
  "identityNote": t("settings-view:identityNote"),
  "language": t("settings-view:language"),
  "languageNote": t("settings-view:languageNote"),
  "light": t("settings-view:light"),
  "loading": t("settings-view:loading"),
  "maintenance": t("settings-view:maintenance"),
  "reconnect": t("settings-view:reconnect"),
  "reconnecting": t("settings-view:reconnecting"),
  "reset": t("settings-view:reset"),
  "save": t("settings-view:save"),
  "saved": t("settings-view:saved"),
  "service": t("settings-view:service"),
  "serviceNote": t("settings-view:serviceNote"),
  "sidebar": t("settings-view:sidebar"),
  "sidebarNote": t("settings-view:sidebarNote"),
  "system": t("settings-view:system"),
  "technical": t("settings-view:technical"),
  "theme": t("settings-view:theme"),
  "themeNote": t("settings-view:themeNote"),
  "title": t("settings-view:title"),
  "tools": t("settings-view:tools"),
  "toolsNote": t("settings-view:toolsNote"),
  "warning": t("settings-view:warning"),
 };
}
