[package]
name = "kanban-store-turso"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
turso = { workspace = true, default-features = false, features = ["fts"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
