[package]
name = "kanban-client"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kanban-protocol = { workspace = true, default-features = false }
kanban-core.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
ureq = { workspace = true, default-features = false, features = ["json"] }

[dev-dependencies]
serde_json.workspace = true
