[package]
name = "kanban-vector-lancedb"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kanban-local.workspace = true
kanban-indexer.workspace = true
clap.workspace = true
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
futures.workspace = true
kanban-entity.workspace = true
kanban-derived-io.workspace = true
kanban-helper-protocol.workspace = true
kanban-vector.workspace = true
lancedb.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
thiserror.workspace = true
tokio.workspace = true
ureq.workspace = true

[dev-dependencies]
tempfile.workspace = true
