[package]
name = "kanban-core"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true
time = { workspace = true, features = ["formatting", "parsing"] }
ulid.workspace = true

[dev-dependencies]
proptest = { workspace = true, default-features = false, features = ["std"] }
