[package]
name = "kanban-application"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
kanban-core.workspace = true
kanban-search.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
